name: Build and Push Docker Image and Deploy to k8s

on:
  push:
    branches:
      - master

env:
  DEPLOYMENT_NAME: coen-chat-deployment # k8s deployment name
  IMG_NAME: poten-test # docker image name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            parkhyuntae/${{ env.IMG_NAME }}:latest
            parkhyuntae/${{ steps.metadata.outputs.tags }}
#            ${{ github.repository_owner }}/${{ env.IMG_NAME }}:latest
#            ${{ github.repository_owner }}/${{ steps.metadata.outputs.tags }}

#      - id: "auth"
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          credentials_json: '${{ secrets.GCP_ACCESS_KEY }}'
#
#      - id: 'test'
#        uses: 'google-github-actions/ssh-compute@v0'
#        with:
#          instance_name: '${{ secrets.GCP_INSTANCE }}'
#          zone: '${{ secrets.GCP_INSTANCE_ZONE }}'
#          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
#          command: 'sudo kubectl set image deployments.apps/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ github.repository_owner }}/${{ steps.metadata.outputs.tags }}'

      - name: switFailNotify
        if: failure()
        run: |
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Github action failed\"}" https://hook.swit.io/chat/230704020620x2fEHM4/lV8EFcPY5xpR7qldXhZO?organization_id=19090600325683321

      - name: switSuccessNotify
        if: success()
        run: |
          curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Github action success\"}" https://hook.swit.io/chat/230704020620x2fEHM4/lV8EFcPY5xpR7qldXhZO?organization_id=19090600325683321